### PR TITLE
Getting repgen into a usable state

### PR DESCRIPTION
**Pull request by DanielTOsborne**
Here's a huge merge which is all the changes I've done at SPK to get repgen into a state where it can finally replace repgen4 entirely.

Included is a script to convert repgen4 report definitions to repgen5 format.

### CODE REVIEW

**Review by MikeNeilson — APPROVED** [review]
Though the build appears to fail.

**Comment by DanielTOsborne** [comment]
> 

Yeah, looks like there's Python 3.5 support I wasn't aware of. I only wrote for 3.6 and higher.

I do also want to add some tests, which is why I created it as a draft.

**Comment by MikeNeilson** [comment]
honestly we can probably drop the python 3.5 support.

**Comment by MikeNeilson** [comment]
when you get a chance drop 3.5 from the list of python version in the .github/workflow/test.yml file. I think that change will be picked up from your end.

**Review by MikeNeilson — COMMENTED** [review]
Excellent.

**Pull request merged**
